export interface Session {
    sessionId: number;
    title: string;
    joinCode?: string;       // Generated by the backend
    status: string;         // 'active', 'completed'
    startAt: Date | string;
    endAt: Date | string;
    createdAt: Date | string;
    employeeId: number;     // The ID of the Host (Mapped to Created_by in SQL)
    creator?: any;          // Navigation property for the Employee
}

export interface CreateSessionRequest {
    title: string;
    employeeId: number;
    startAt: string;        // Sent as ISO String
    endAt: string;          // Sent as ISO String
    status: string;
}